plugins {
    id 'java'
    id 'war'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {

    // Servlet API cho Tomcat 10
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    // Spring 6
    implementation 'org.springframework:spring-webmvc:6.1.8'

    // Thymeleaf Spring 6
    implementation 'org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
}

test {
    useJUnitPlatform()
}